development:
  adapter: postgresql
  database: sleepphones_development
  pool: 5
  username: sleepphones
  password:

test:
  adapter: postgresql
  database: sleepphones_test
  pool: 5
  username: sleepphones
  password:

production:
  adapter: postgresql
  database: sleepphones_production
  pool: 5
  username: sleepphones
  password:
